name: PR CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i package lock
        run: npm install --package-lock-only
      - name: npm install
        run: npm ci
      - name: build
        run: npm run lerna run build

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i package lock
        run: npm install --package-lock-only
      - name: npm install
        run: npm ci
      - name: test
        run: npm run lerna run test

  validate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.20.0]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm i package lock
        run: npm install --package-lock-only
      - name: npm install
        run: npm ci
      - name: validate commits
        run: node ./node_modules/@valueadd/dev validate-commit origin/master
      - name: prettier check
        run: node ./node_modules/@valueadd/dev prettier-check `git diff origin/master  --cached --name-only --diff-filter=AM | tr '\r\n' ','`
      - name: lint
        run: npm run lint
